#ifndef _CONSTS_H_
#define _CONSTS_H_

#include "config.h"

#define SIDERAL_DAY_MS 86164000UL
#define SOLAR_DAY_MS 86400000UL
#define LUNAR_DAY_MS 88253300UL

#define MAX_MICROSTEPS 256UL

#define GEAR_RATIO 101.25

#define STEPS_PER_TRACKER_FULL_REV (STEPPER_STEPS_PER_REV * GEAR_RATIO * MAX_MICROSTEPS)

#endif /* _CONSTS_H_ */
