/**
 * @file error.h
 * @version 0.1.0
 *
 * @section License
 * Copyright (C) 2025, Sylensky
 */

#ifndef ERROR_H
#define ERROR_H

enum ErrorMessage
{
    ERR_MSG_INVALID_CAPTURE_MODE,
    ERR_MSG_INVALID_EXPOSURE_LENGTH,
    ERR_MSG_INVALID_EXPOSURE_AMOUNT,
    ERR_MSG_INVALID_PREDELAY_TIME,
    ERR_MSG_INVALID_DELAY_TIME,
    ERR_MSG_INVALID_FRAME_AMOUNT,
    ERR_MSG_INVALID_PAN_ANGLE,
    ERR_MSG_INVALID_PAN_DIRECTION,
    ERR_MSG_INVALID_ENABLE_TRACKING_VALUE,
    ERR_MSG_INVALID_DITHER_CHOICE,
    ERR_MSG_INVALID_DITHER_FREQUENCY,
    ERR_MSG_INVALID_FOCAL_LENGTH,
    ERR_MSG_INVALID_PIXEL_SIZE,

    // Do not change below this line
    ERR_MSG_NONE,
    NUMBER_OF_ERROR_MESSAGES,
};

#endif
